version: "3.8"
services:
  contacthub-db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=contacthub
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: contacthub-db