version: '3'
services:
  contacthub-db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=contacthub
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: contacthub-db
  contacthub-app:
    build:
      context: ../
      dockerfile: ./docker-compose/Dockerfile
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE='docker'
    depends_on:
      - contacthub-db
